### ISSUE TITLE
Preventing disabled plugins from being refreshed

### ISSUE THREAD

**Issue by Xrayez** [willnationsdev/godot-plugin-refresher#5]
I've accidentally reloaded a plugin which was supposed to be disabled because it's not functioning (aka WIP). I wonder whether it might be worth to:

* hide initially disabled plugins from the popup;
* disallow to reload disabled plugins, emitting a warning.

So the idea is to only to reload plugins which are actually enabled.

This could be made optional via plugin settings support which was added in #3.

Not that it's critical though because the reloaded plugin stays on now, making it less likely to reload a WIP plugin.

**Comment by willnationsdev** [comment]
This sounds like a good idea. Feel free to tackle it if interested. I don't think we need to make it optional since it's the intended behavior of the plugin anyway. It doesn't make any sense to "reload" something that isn't active to begin with.

> - hide initially disabled plugins from the popup;
> - disallow to reload disabled plugins, emitting a warning.

I would just add these features. Technically, the first feature should keep the first from ever happening, but if someone attempted to use the plugin to manually refresh an inactive plugin rather than using the dropdown, then the second feature would come in handy.
